version: "3.9"
services:
  github_runner:
    # build: .
    image: ghcr.io/pagopa/github-self-hosted-runner-azure:beta-kubelogin-setup
    environment:
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}


