version: "3.9"

services:

  github_runner:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
