name: Check for New Release and Update Dockerfile

on:
  # schedule:
  #   - cron: '0 * * * *' # Execute every hour
  workflow_dispatch:
  push:
    branches:
      - EC-340-action-update-dockerfile

jobs:
  check-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        name: Checkout
    
      - name: Get latest release from another repo
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const latestRelease = await github.rest.repos.getLatestRelease({
              owner: 'actions',
              repo: 'runner'
            });
            return {
              tag_name: latestRelease.data.tag_name,
              sha: latestRelease.data.target_commitish,
            };
            
      - name: Debug latest release
        run: |
          echo "Latest release tag: ${{ steps.get_release.outputs.tag_name }}"
          echo "Latest release sha: ${{ steps.get_release.outputs.sha }}"
