name: Check for New Release and Update Dockerfile

on:
  # schedule:
  #   - cron: '0 * * * *' # Execute every hour
  workflow_dispatch:
  push:
    branches:
      - EC-340-action-update-dockerfile

jobs:
  check-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        name: Checkout
    
      - name: Get latest release from another repo
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const latestRelease = await github.rest.repos.getLatestRelease({
              owner: 'actions',
              repo: 'runner'
            });
            const releaseInfo = {
              tag_name: latestRelease.data.tag_name,
              sha: latestRelease.data.target_commitish,
            };
            console.log(JSON.stringify(releaseInfo));
            return JSON.stringify(releaseInfo);
            
      - name: Define release outputs
        id: release_outputs
        run: |
          release_info="${{ steps.get_release.outputs.result }}"  
          tag_name=$(echo "$release_info" | jq -r '.tag_name')
          sha=$(echo "$release_info" | jq -r '.sha')

          echo "tag_name=$tag_name" >> "$GITHUB_OUTPUT"
          echo "sha=$sha" >> "$GITHUB_OUTPUT"

      - name: Get changelog file
        id: changelog
        run: |
          if [ ! -f CHANGELOG.md ]; then
            echo "Changelog file does not exist. Creating one..."
            touch CHANGELOG.md
          fi

      - name: Update Changelog
        id: update_changelog
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const changelogPath = 'CHANGELOG.md';
            const dockerImage = `docker pull ghcr.io/actions/runner:${{ steps.release_outputs.outputs.tag_name }}@sha256:${{ steps.release_outputs.outputs.sha }}`;
  
            const changelogEntry = `## ${{ steps.release_outputs.outputs.tag_name }}\n- Docker Image: \`${dockerImage}\`\n`;
  
            const changelogContent = fs.readFileSync(changelogPath, 'utf8');
            fs.writeFileSync(changelogPath, `${changelogEntry}\n${changelogContent}`);
    
      - name: Debug changelog file
        run: cat CHANGELOG.md