name: Check for New Release and Update Dockerfile

on:
  # schedule:
  #   - cron: '0 * * * *' # Execute every hour
  workflow_dispatch:
  push:
    branches:
      - EC-340-action-update-dockerfile

jobs:
  check-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        name: Checkout
    
      - name: Get latest release from another repo
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const latestRelease = await github.rest.repos.getLatestRelease({
              owner: 'actions',
              repo: 'runner'
            });
            
            const asset = latestRelease.data.assets.find(asset => asset.name.includes('linux-x64'));

            if (!asset) {
              throw new Error('Could not find linux/amd64 asset in the release');
            }

            const assetDetails = await github.rest.repos.getReleaseAsset({
              owner: 'actions',
              repo: 'runner',
              asset_id: asset.id
            });

            const releaseInfo = {
              tag_name: latestRelease.data.tag_name,
              sha: assetDetails.data.target_commitish,
            };
            console.log(JSON.stringify(releaseInfo));
            return JSON.stringify(releaseInfo);
            
      - name: Define release outputs
        id: release_outputs
        run: |
          release_info="${{ steps.get_release.outputs.result }}"  
          tag_name=$(echo "$release_info" | jq -r '.tag_name')
          sha=$(echo "$release_info" | jq -r '.sha')

          echo "tag_name=$tag_name" >> "$GITHUB_OUTPUT"
          echo "sha=$sha" >> "$GITHUB_OUTPUT"

      - name: Check if release has changed
        id: check_release_changes
        run: |
          current_tag=$(jq -r '.current_tag' release.json)
          current_sha=$(jq -r '.current_sha' release.json)
          new_tag=${{ steps.release_outputs.outputs.tag_name }}
          new_sha=${{ steps.release_outputs.outputs.sha }}

          if [[ "$current_tag" == "$new_tag" && "$current_sha" == "$new_sha" ]]; then
            echo "No changes in release."
            echo "release_changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "Release has changed."
            echo "release_changed=true" >> "$GITHUB_OUTPUT"
            # Update release.json
            jq -n --arg new_tag "$new_tag" --arg new_sha "$new_sha" \
              '{current_tag: $new_tag, current_sha: $new_sha}' > release.json

            cat release.json
          fi

      - name: Get changelog file
        id: changelog
        run: |
          if [ ! -f CHANGELOG.md ]; then
            echo "Changelog file does not exist. Creating one..."
            touch CHANGELOG.md
          fi

      - name: Update Changelog
        if: steps.check_release_changes.outputs.release_changed == 'true'
        id: update_changelog
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const changelogPath = 'CHANGELOG.md';
            const dockerImage = `docker pull ghcr.io/actions/runner:${{ steps.release_outputs.outputs.tag_name }}@sha256:${{ steps.release_outputs.outputs.sha }}`;
  
            const changelogEntry = `## ${{ steps.release_outputs.outputs.tag_name }}\n- Docker Image: \`${dockerImage}\`\n`;
  
            const changelogContent = fs.readFileSync(changelogPath, 'utf8');
            fs.writeFileSync(changelogPath, `${changelogEntry}\n${changelogContent}`);
    
      - name: Update Dockerfile
        if: steps.check_release_changes.outputs.release_changed == 'true'
        id: update_dockerfile
        run: |
          echo "Updating Dockerfile..."

          # Construct the new FROM statement
          new_from="FROM ghcr.io/actions/actions-runner:${{ steps.release_outputs.outputs.tag_name }}@${{ steps.release_outputs.outputs.sha }} AS base"
          
          # Replace the first line with the new FROM statement
          sed -i "1s|.*|$new_from|" Dockerfile

          echo "Dockerfile updated."
          cat Dockerfile

      - name: Debug changelog file
        run: |
          echo "CHANGELOG.md content:"
          cat CHANGELOG.md